import React from 'react'
import styles from "./footer.module.css"
import Image from 'next/image'
import Link from 'next/link'

const Footer = () => {
    return (
        <div 
            className={styles.container}
        >
            <div 
                className={styles.info}
            >
                <div 
                    className={styles.logo}
                >
                    <Image 
                        src="/logo.png" 
                        alt="Quantumize" 
                        width={50} 
                        height={50}
                    />
                    <h1
                        className={styles.logoText}
                    >
                        Quantumize
                    </h1>
                </div>
                <p
                    className={styles.desc}
                >
                    ©2024 All rights reserved | Designed by: Ankit Kumar Pandit
                </p>
                <div
                    className={styles.icons}
                >
                    <Image 
                        src="/facebook.png" 
                        alt="Facebook" 
                        width={18} 
                        height={18}
                    />
                    <Image 
                        src="/instagram.png" 
                        alt="Instagram" 
                        width={18} 
                        height={18}
                    />
                    <Image 
                        src="/twitter.png" 
                        alt="X" 
                        width={18} 
                        height={18}
                    />
                    <Image 
                        src="/github.png" 
                        alt="Github" 
                        width={18} 
                        height={18}
                    />
                </div>
            </div>
            <div 
                className={styles.links}
            >
                <div 
                    className={styles.list}
                >
                    <span
                        className={styles.listTitle}
                    >
                        Links
                    </span>
                    <Link
                        href="/"
                    >
                        Homepage
                    </Link>
                    <Link
                        href="/"
                    >
                        Blog
                    </Link>
                    <Link
                        href="/"
                    >
                        About
                    </Link>
                    <Link
                        href="/"
                    >
                        Contact
                    </Link>
                    <Link
                        href="/"
                    >
                        Login
                    </Link>
                </div>
                <div 
                    className={styles.list}
                >
                    <span
                        className={styles.listTitle}
                    >
                        Tags
                    </span>
                    <Link
                        href="/"
                    >
                        Style
                    </Link>
                    <Link
                        href="/"
                    >
                        Fashion
                    </Link>
                    <Link
                        href="/"
                    >
                        Food
                    </Link>
                    <Link
                        href="/"
                    >
                        Travel
                    </Link>
                    <Link
                        href="/"
                    >
                        Culture
                    </Link>
                    <Link
                        href="/"
                    >
                        Coding
                    </Link>
                </div>
                <div 
                    className={styles.list}
                >
                    <span
                        className={styles.listTitle}
                    >
                        Social
                    </span>
                    <Link
                        href="/"
                    >
                        Facebook
                    </Link>
                    <Link
                        href="/"
                    >
                        Instagram
                    </Link>
                    <Link
                        href="/"
                    >
                        X
                    </Link>
                    <Link
                        href="/"
                    >
                        Github
                    </Link>
                </div>
            </div>
        </div>
    )
}

export default Footer